imp:
  imp_key: 5657554032853018
  imp_secret: GqLIePegZt4w0QKvBt1NZ4eKie8tNoILe9oVbhgbVegQJawM5ciwsCXzswRJAqb8NTgpTQBtWdQ2Stym
spring:
  jwt:
    secret: 12345678901234567890123456789012
  datasource:
    url:  jdbc:mariadb://123.123.123.124:3306/FIIIIIVE
    username: snk
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: okqkrwhdtjd@gmail.com
    password: hacp nwtq rezf rnml
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace